# Generated by Django 4.0 on 2025-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_attribute_attributevalue_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
